### ISSUE TITLE
Control may reach end of non-void function error on scanhandler.c

### ISSUE THREAD

**Issue by daswareinfach** [DuffyAPP-IT/ZPET#1]
![Screen Shot 2020-06-06 at 23 31 40](https://user-images.githubusercontent.com/35432275/83954002-e1a73000-a84d-11ea-8edf-09cb91b14812.png)

**Comment by DuffyAPP-IT** [comment]
Thanks! I'll check this out ASAP.

**Comment by DuffyAPP-IT** [comment]
Fixed!
