### ISSUE TITLE
Support for Filesystem Rather Than Just Live Devices?

### ISSUE THREAD

**Issue by chipriley** [DuffyAPP-IT/ZPET#3]
Any chances that you’ll build in support for working with data in addition to live devices? You know, for those of us who might have capabilities to work with BFU data from non-checkm8-vulnerable devices. 

Thanks for all your work!

**Comment by DuffyAPP-IT** [comment]
Hi! Thanks for the comment and kind words. Support for processing tar's etc is currently in the works - hoping to have this feature added in the next week or two! (not so many changes required under the hood)

**Comment by chipriley** [comment]
Sounds great.  I'll close this issue so that it's not the only one lingering around...
